// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUldGZ4o-yz5F8TYCKuY6C_RNHDKTxn9c',
    appId: '1:45228980126:web:cca8a0fc7420b58d19088f',
    messagingSenderId: '45228980126',
    projectId: 'career-55076',
    authDomain: 'career-55076.firebaseapp.com',
    storageBucket: 'career-55076.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF5gbyFglRqprUm_DD5WT4gWIpedu6xIM',
    appId: '1:45228980126:android:beb0fb2cb01604db19088f',
    messagingSenderId: '45228980126',
    projectId: 'career-55076',
    storageBucket: 'career-55076.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnTsiLWH2pAXoYpU_JaO_CUDnbP6fV_38',
    appId: '1:45228980126:ios:3f024100e5c6ffa319088f',
    messagingSenderId: '45228980126',
    projectId: 'career-55076',
    storageBucket: 'career-55076.firebasestorage.app',
    iosBundleId: 'com.example.collage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUldGZ4o-yz5F8TYCKuY6C_RNHDKTxn9c',
    appId: '1:45228980126:web:449b92edfe73024419088f',
    messagingSenderId: '45228980126',
    projectId: 'career-55076',
    authDomain: 'career-55076.firebaseapp.com',
    storageBucket: 'career-55076.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnTsiLWH2pAXoYpU_JaO_CUDnbP6fV_38',
    appId: '1:45228980126:ios:3f024100e5c6ffa319088f',
    messagingSenderId: '45228980126',
    projectId: 'career-55076',
    storageBucket: 'career-55076.firebasestorage.app',
    iosBundleId: 'com.example.collage',
  );

}